project:
  type: website
  output-dir: docs

website:
  title: "Adrian Perez"
  search: false
  google-analytics: "G-WY4T41ZBM7"
  navbar:
    background: primary
    left:
    - icon: file-text
      text: CV
      href: curriculum-vitae.qmd
    - icon: file-earmark-pdf
      text: Resume
      href: https://drive.google.com/file/d/16LUU_QZkhDRfBsBKhnfO0xAU3CweNek_/view

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
