project:
  type: website
  output-dir: docs

website:
  title: "Jesus Adrian Perez"
  search: false
  google-analytics: 
    tracking-id: "G-WY4T41ZBM7"
    storage: none
  navbar:
    background: primary
    left:
    - href: curriculum-vitae.qmd
      text: CV
      icon: file-text

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
