project:
  type: website
  output-dir: docs

website:
  title: "Jesus Adrian Perez"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: About Me
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

