project:
  type: website
  output-dir: docs

website:
  title: "Jesus Adrian Perez"
  search: false
  google-analytics: "G-262817704"
  navbar:
    background: primary
    left:
    - icon: file-text
      text: CV
      href: curriculum-vitae.qmd

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
