project:
  type: website
  output-dir: docs

website:
  title: "Jesus Adrian Perez"
  icon: emoji-sunglasses-fill
  search: false
  navbar:
    background: primary

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
